### ISSUE TITLE
SPGLIB dependency conflict

### ISSUE THREAD

**Issue by IsaacSugden** [CCP-NC/orgdisord#1]
* orgdisord version: 2024/02//28 fresh conda install
* Python version: 3.11
* Operating System: WSL

### Description
2 ordered forms passed to orgdisord to create ensemble:
orgdisord enumerate ABABUB_maj.xyz ABABUB_min.xyz
TypeError in splib.py line 1985 - float() Arg must be a string or a real number, not 'Atom'

### What I Did

Issue traced to version of spglib -> v2.20 runs without issue, 2.3.1 introduces this breaking error. conda installed to the older version and runs fine, but dependencies will need to be looked at down the line I guess

**Comment by jkshenton** [comment]
Thanks for reporting this Isaac - I think this is fixed now for clean installs

**Comment by IsaacSugden** [comment]
looks gorgeous mate, can confirm clean install working
